### PR TITLE
Add blocking docker create

### PR DESCRIPTION
**Pull request by MaralAfris**
Added support for the docker create command.
It takes forever so that is why I added a _run_blocking definition, using the blocking approach is triggered by the blocking argument.

### CODE REVIEW

**Comment by gijzelaerr** [comment]
awesome! looking good. Can you maybe extend the test suite so it tests the create command both blocking and not-blocking?

**Comment by MaralAfris** [comment]
On it ;)

**Comment by MaralAfris** [comment]
Good enough ?
Can't test on the airport wifi but hope it passes ;)

**Comment by gijzelaerr** [comment]
perfect!

**Comment by gijzelaerr** [comment]
made a new 0.2.2 release!

**Comment by MaralAfris** [comment]
Great :)

**Pull request merged**
